import type {
  CanonicalActivityDefinition,
  LaunchCityRelevance,
  LaunchVisibleActivityPolicy,
  VenueTypeId,
} from './types';

type BaseCanonicalActivityDefinition = Omit<CanonicalActivityDefinition, 'launchVisibility'>;

const weights = {
  manual_override: 1,
  session_evidence: 0.97,
  venue_activity_mapping: 0.92,
  explicit_provider_tag: 0.9,
  exact_taxonomy_match: 0.84,
  provider_category_match: 0.76,
  name_alias: 0.68,
  compatible_venue_type: 0.58,
  generic_context: 0.24,
  hard_negative: -0.92,
} as const;

const launchAll = (relevance: LaunchCityRelevance) => ({ hanoi: relevance, 'da-nang': relevance, bangkok: relevance }) as const;
const launchCore = { hanoi: 'priority', 'da-nang': 'supported', bangkok: 'priority' } as const;
const consumeristHardNegatives = ['restaurant', 'bar', 'cafe', 'coffee', 'lounge', 'rooftop', 'retail', 'mall', 'shop', 'nightclub'];
const genericOutdoorNegatives = ['generic park', 'garden', 'plaza', 'community building', 'cultural house'];
const creativeNegatives = ['gift shop', 'souvenir', 'retail'];

const _sportsCentre = ['sports-centre', 'court', 'pitch'] as VenueTypeId[];
const communityIndoor = ['community-centre', 'cultural-centre'] as VenueTypeId[];

const VENUE_EVIDENCE_POLICY: LaunchVisibleActivityPolicy = {
  visibilityMode: 'venue_only',
  browseVisibilityThreshold: 0.58,
  specificQueryThreshold: 0.82,
  suppressGenericShapes: true,
  allowedAreaShapes: [],
};

const PROGRAM_ONLY_POLICY: LaunchVisibleActivityPolicy = {
  visibilityMode: 'program_only',
  browseVisibilityThreshold: 0.6,
  specificQueryThreshold: 0.82,
  suppressGenericShapes: true,
  allowedAreaShapes: [],
};

const OUTDOOR_AREA_POLICY: LaunchVisibleActivityPolicy = {
  visibilityMode: 'area_ok',
  browseVisibilityThreshold: 0.56,
  specificQueryThreshold: 0.78,
  suppressGenericShapes: true,
  allowedAreaShapes: ['park', 'walking-route', 'running-track', 'trail-network', 'mountain-trail', 'cycling-route', 'bike-park', 'beach'],
};

const launchVisibilityOverrides: Record<string, LaunchVisibleActivityPolicy> = {
  running: OUTDOOR_AREA_POLICY,
  'trail-running': OUTDOOR_AREA_POLICY,
  walking: {
    ...OUTDOOR_AREA_POLICY,
    browseVisibilityThreshold: 0.5,
    specificQueryThreshold: 0.7,
    allowedAreaShapes: ['park', 'walking-route', 'trail-network', 'mountain-trail'],
  },
  hiking: {
    ...OUTDOOR_AREA_POLICY,
    specificQueryThreshold: 0.82,
    allowedAreaShapes: ['park', 'trail-network', 'mountain-trail'],
  },
  cycling: {
    ...OUTDOOR_AREA_POLICY,
    specificQueryThreshold: 0.76,
    allowedAreaShapes: ['cycling-route', 'bike-park', 'trail-network'],
  },
  'mountain-biking': {
    ...OUTDOOR_AREA_POLICY,
    specificQueryThreshold: 0.84,
    allowedAreaShapes: ['bike-park', 'trail-network', 'mountain-trail'],
  },
  bmx: {
    ...OUTDOOR_AREA_POLICY,
    specificQueryThreshold: 0.86,
    allowedAreaShapes: ['bike-park'],
  },
  mountaineering: {
    ...OUTDOOR_AREA_POLICY,
    specificQueryThreshold: 0.86,
    allowedAreaShapes: ['mountain-trail', 'trail-network'],
  },
  yoga: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.6, specificQueryThreshold: 0.78 },
  pilates: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.6, specificQueryThreshold: 0.8 },
  barre: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.6, specificQueryThreshold: 0.82 },
  mobility: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.78 },
  stretching: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.78 },
  meditation: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.82 },
  breathwork: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  dancing: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.76 },
  salsa: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.82 },
  bachata: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.82 },
  tango: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  'hip-hop': { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  'contemporary-dance': { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  ballet: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  'pole-dance': { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  aerial: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.86 },
  chess: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  'board games': { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.82 },
  pottery: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
  ceramics: { ...PROGRAM_ONLY_POLICY, browseVisibilityThreshold: 0.58, specificQueryThreshold: 0.84 },
};

const resolveLaunchVisibilityPolicy = (definition: BaseCanonicalActivityDefinition): LaunchVisibleActivityPolicy => {
  const override = launchVisibilityOverrides[definition.id];
  if (override) return override;
  return VENUE_EVIDENCE_POLICY;
};

const CANONICAL_ACTIVITY_DEFINITIONS = [
  {
    id: 'climbing',
    displayLabel: 'Climbing',
    aliases: ['climbing', 'rock climbing', 'indoor climbing', 'leo nui', 'ปีนผา', 'ยิมปีนผา'],
    family: 'climbing',
    allowedVenueTypes: ['climbing-gym', 'sports-centre'],
    preferredProviderCategories: {
      osmTags: [{ key: 'sport', values: ['climbing'] }, { key: 'leisure', values: ['sports_centre'] }],
      googleTypes: ['gym', 'rock_climbing_gym', 'sports_complex'],
      foursquareCategoryIds: ['4bf58dd8d48988d1e1931735'],
      foursquareLabels: ['rock climbing gym', 'climbing gym'],
      internalTaxonomy: ['climbing-bouldering-labs'],
    },
    hardNegatives: [...consumeristHardNegatives, ...genericOutdoorNegatives],
    confidenceWeights: weights,
    queryIntent: { aliases: ['climb', 'climbing gym'], specificMinScore: 0.8, browseMinScore: 0.46, requireStrongEvidenceForSpecific: true },
    launchCityRelevance: launchCore,
    legacyCatalogId: 3,
  },
  {
    id: 'bouldering',
    displayLabel: 'Bouldering',
    aliases: ['bouldering', 'boulder gym', 'boulder', 'โบลเดอร์', 'ยิมปีนผา'],
    family: 'climbing',
    allowedVenueTypes: ['climbing-gym'],
    preferredProviderCategories: {
      osmTags: [{ key: 'sport', values: ['climbing'] }],
      googleTypes: ['rock_climbing_gym', 'gym'],
      foursquareLabels: ['bouldering gym', 'rock climbing gym'],
      internalTaxonomy: ['climbing-bouldering-labs'],
    },
    hardNegatives: [...consumeristHardNegatives, ...genericOutdoorNegatives],
    confidenceWeights: weights,
    queryIntent: { aliases: ['boulder', 'bouldering gym'], specificMinScore: 0.82, browseMinScore: 0.48, requireStrongEvidenceForSpecific: true },
    launchCityRelevance: launchCore,
    legacyCatalogId: 17,
  },
  { id: 'mountaineering', displayLabel: 'Mountaineering', aliases: ['mountaineering', 'alpinism', 'summit training'], family: 'climbing', allowedVenueTypes: ['mountain-trail', 'climbing-gym'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['climbing'] }, { key: 'route', values: ['hiking'] }], googleTypes: ['hiking_area'], foursquareLabels: ['mountain', 'trail'], internalTaxonomy: ['sunrise-hike-crews'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['alpine', 'mountain climb'], specificMinScore: 0.86, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'supported', bangkok: 'optional' }, searchable: true },
  { id: 'running', displayLabel: 'Running', aliases: ['running', 'run club', 'jogging', 'chạy bộ', 'วิ่ง'], family: 'outdoor-recreation', allowedVenueTypes: ['running-track', 'trail-network', 'walking-route', 'park'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['running', 'athletics'] }, { key: 'leisure', values: ['track'] }], googleTypes: ['stadium', 'park', 'gym'], foursquareLabels: ['track stadium', 'running track'], internalTaxonomy: ['city-run-crews', 'trail-running-escapes'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['run', 'run club', 'jog'], specificMinScore: 0.76, browseMinScore: 0.4, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), legacyCatalogId: 10 },
  { id: 'trail-running', displayLabel: 'Trail Running', aliases: ['trail running', 'singletrack run'], family: 'outdoor-recreation', allowedVenueTypes: ['trail-network', 'mountain-trail'], preferredProviderCategories: { osmTags: [{ key: 'route', values: ['hiking'] }, { key: 'highway', values: ['path', 'track'] }], googleTypes: ['hiking_area', 'park'], foursquareLabels: ['trail', 'hiking trail'], internalTaxonomy: ['trail-running-escapes'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['trail run'], specificMinScore: 0.84, browseMinScore: 0.36, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'priority', bangkok: 'optional' }, searchable: true },
  { id: 'walking', displayLabel: 'Walking', aliases: ['walking', 'walk club', 'walking group'], family: 'outdoor-recreation', allowedVenueTypes: ['walking-route', 'park', 'community-centre'], preferredProviderCategories: { osmTags: [{ key: 'highway', values: ['footway', 'pedestrian', 'path'] }], googleTypes: ['park'], foursquareLabels: ['park', 'plaza'], internalTaxonomy: ['architecture-walks', 'neighborhood-clean-walks'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['walk', 'walking group'], specificMinScore: 0.7, browseMinScore: 0.34, requireStrongEvidenceForSpecific: false }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'hiking', displayLabel: 'Hiking', aliases: ['hiking', 'hike', 'trekking'], family: 'outdoor-recreation', allowedVenueTypes: ['mountain-trail', 'trail-network'], preferredProviderCategories: { osmTags: [{ key: 'route', values: ['hiking'] }, { key: 'highway', values: ['path', 'track'] }], googleTypes: ['hiking_area', 'park'], foursquareLabels: ['hiking trail', 'trail'], internalTaxonomy: ['sunrise-hike-crews'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['trek'], specificMinScore: 0.82, browseMinScore: 0.38, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'priority', 'da-nang': 'priority', bangkok: 'optional' }, searchable: true },
  { id: 'cycling', displayLabel: 'Cycling', aliases: ['cycling', 'bike ride', 'bicycle', 'cycling club'], family: 'cycling', allowedVenueTypes: ['cycling-route', 'bike-park', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['cycling'] }, { key: 'route', values: ['bicycle'] }], googleTypes: ['bicycle_store', 'gym', 'sports_complex'], foursquareLabels: ['cycle studio', 'bike shop', 'cycling club'], internalTaxonomy: ['tempo-cycling-meetups'] }, hardNegatives: ['bike rental', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['bike', 'biking'], specificMinScore: 0.76, browseMinScore: 0.36, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), legacyCatalogId: 11 },
  { id: 'mountain-biking', displayLabel: 'Mountain Biking', aliases: ['mountain biking', 'mtb'], family: 'cycling', allowedVenueTypes: ['bike-park', 'trail-network'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['cycling'] }, { key: 'mtb:scale', values: ['0', '1', '2', '3'] }], googleTypes: ['hiking_area', 'park'], foursquareLabels: ['bike trail'], internalTaxonomy: [] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['mtb'], specificMinScore: 0.84, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'priority', bangkok: 'optional' }, searchable: true },
  { id: 'bmx', displayLabel: 'BMX', aliases: ['bmx', 'bmx park'], family: 'cycling', allowedVenueTypes: ['bike-park'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['bmx'] }], googleTypes: ['park'], foursquareLabels: ['skate park', 'bike park'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['bmx biking'], specificMinScore: 0.86, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'supported', bangkok: 'optional' }, searchable: true },
  { id: 'spin', displayLabel: 'Spin', aliases: ['spin', 'indoor cycling', 'spin class'], family: 'cycling', allowedVenueTypes: ['spin-studio', 'gym'], preferredProviderCategories: { osmTags: [{ key: 'leisure', values: ['fitness_centre'] }], googleTypes: ['gym'], foursquareLabels: ['cycle studio', 'spin studio'], internalTaxonomy: ['tempo-cycling-meetups'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['spin studio'], specificMinScore: 0.78, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'yoga', displayLabel: 'Yoga', aliases: ['yoga', 'vinyasa', 'hatha yoga', 'โยคะ', 'thiền yoga'], family: 'movement-wellness', allowedVenueTypes: ['yoga-studio', 'wellness-studio', 'community-centre'], preferredProviderCategories: { osmTags: [{ key: 'leisure', values: ['fitness_centre', 'sports_centre'] }], googleTypes: ['yoga_studio', 'gym'], foursquareCategoryIds: ['4bf58dd8d48988d102941735'], foursquareLabels: ['yoga studio', 'meditation center'], internalTaxonomy: ['vinyasa-flow-sessions'] }, hardNegatives: [...consumeristHardNegatives, 'generic park'], confidenceWeights: weights, queryIntent: { aliases: ['yoga studio', 'flow yoga'], specificMinScore: 0.78, browseMinScore: 0.44, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), legacyCatalogId: 4 },
  { id: 'pilates', displayLabel: 'Pilates', aliases: ['pilates', 'reformer pilates', 'mat pilates'], family: 'movement-wellness', allowedVenueTypes: ['pilates-studio', 'wellness-studio'], preferredProviderCategories: { osmTags: [{ key: 'leisure', values: ['fitness_centre'] }], googleTypes: ['pilates_studio', 'gym'], foursquareLabels: ['pilates studio'], internalTaxonomy: ['pilates-mat-labs'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['pilates studio', 'reformer'], specificMinScore: 0.8, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'barre', displayLabel: 'Barre', aliases: ['barre', 'barre studio'], family: 'movement-wellness', allowedVenueTypes: ['barre-studio', 'wellness-studio'], preferredProviderCategories: { googleTypes: ['gym'], foursquareLabels: ['barre studio'], internalTaxonomy: [] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['barre class'], specificMinScore: 0.82, browseMinScore: 0.38, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'mobility', displayLabel: 'Mobility', aliases: ['mobility', 'mobility class', 'movement prep'], family: 'movement-wellness', allowedVenueTypes: ['wellness-studio', 'gym'], preferredProviderCategories: { googleTypes: ['gym'], foursquareLabels: ['fitness center'], internalTaxonomy: ['mobility-reset-circuits'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['mobility training'], specificMinScore: 0.78, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'stretching', displayLabel: 'Stretching', aliases: ['stretching', 'stretch class'], family: 'movement-wellness', allowedVenueTypes: ['wellness-studio', 'gym'], preferredProviderCategories: { googleTypes: ['gym'], foursquareLabels: ['fitness center'], internalTaxonomy: ['mobility-reset-circuits'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['stretch'], specificMinScore: 0.78, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'gym', displayLabel: 'Gym', aliases: ['gym', 'fitness centre', 'fitness center', 'gym workout'], family: 'strength-fitness', allowedVenueTypes: ['gym', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'leisure', values: ['fitness_centre', 'sports_centre'] }], googleTypes: ['gym', 'sports_complex'], foursquareLabels: ['gym / fitness center'], internalTaxonomy: ['functional-fitness-pods'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['fitness gym'], specificMinScore: 0.72, browseMinScore: 0.42, requireStrongEvidenceForSpecific: false }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'strength-training', displayLabel: 'Strength Training', aliases: ['strength training', 'weight training', 'lifting'], family: 'strength-fitness', allowedVenueTypes: ['gym', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'leisure', values: ['fitness_centre'] }], googleTypes: ['gym'], foursquareLabels: ['gym / fitness center'], internalTaxonomy: ['functional-fitness-pods'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['weights', 'lifting gym'], specificMinScore: 0.8, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'crossfit', displayLabel: 'CrossFit', aliases: ['crossfit', 'cross fit', 'cf box'], family: 'strength-fitness', allowedVenueTypes: ['crossfit-box', 'gym'], preferredProviderCategories: { googleTypes: ['gym'], foursquareLabels: ['crossfit gym'], internalTaxonomy: ['functional-fitness-pods'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['crossfit box'], specificMinScore: 0.82, browseMinScore: 0.4, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'hiit', displayLabel: 'HIIT', aliases: ['hiit', 'high intensity interval training'], family: 'strength-fitness', allowedVenueTypes: ['gym', 'crossfit-box'], preferredProviderCategories: { googleTypes: ['gym'], foursquareLabels: ['gym / fitness center'], internalTaxonomy: ['functional-fitness-pods'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['interval training'], specificMinScore: 0.8, browseMinScore: 0.36, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'functional-fitness', displayLabel: 'Functional Fitness', aliases: ['functional fitness', 'circuit training'], family: 'strength-fitness', allowedVenueTypes: ['gym', 'crossfit-box'], preferredProviderCategories: { googleTypes: ['gym'], foursquareLabels: ['gym / fitness center'], internalTaxonomy: ['functional-fitness-pods'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['functional training'], specificMinScore: 0.8, browseMinScore: 0.36, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'boxing', displayLabel: 'Boxing', aliases: ['boxing', 'boxing gym', 'muay thai boxing'], family: 'martial-arts', allowedVenueTypes: ['boxing-gym', 'martial-arts-gym'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['boxing'] }], googleTypes: ['gym'], foursquareLabels: ['boxing gym', 'martial arts dojo'], internalTaxonomy: ['boxing-combat-labs'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['box', 'boxing class'], specificMinScore: 0.84, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'kickboxing', displayLabel: 'Kickboxing', aliases: ['kickboxing', 'muay thai', 'muaythai'], family: 'martial-arts', allowedVenueTypes: ['boxing-gym', 'martial-arts-gym'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['kickboxing', 'muay_thai'] }], googleTypes: ['gym'], foursquareLabels: ['boxing gym', 'martial arts dojo'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['muay thai gym'], specificMinScore: 0.84, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'judo', displayLabel: 'Judo', aliases: ['judo'], family: 'martial-arts', allowedVenueTypes: ['martial-arts-gym'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['judo'] }], googleTypes: ['gym'], foursquareLabels: ['martial arts dojo'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['judo dojo'], specificMinScore: 0.86, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'bjj', displayLabel: 'Brazilian Jiu-Jitsu', aliases: ['bjj', 'jiu-jitsu', 'brazilian jiu jitsu'], family: 'martial-arts', allowedVenueTypes: ['martial-arts-gym'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['jiu_jitsu'] }], googleTypes: ['gym'], foursquareLabels: ['martial arts dojo'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['jiu jitsu dojo'], specificMinScore: 0.86, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'mma', displayLabel: 'MMA', aliases: ['mma', 'mixed martial arts'], family: 'martial-arts', allowedVenueTypes: ['martial-arts-gym'], preferredProviderCategories: { googleTypes: ['gym'], foursquareLabels: ['martial arts dojo'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['mma gym'], specificMinScore: 0.86, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'fencing', displayLabel: 'Fencing', aliases: ['fencing', 'fencing club'], family: 'martial-arts', allowedVenueTypes: ['fencing-club', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['fencing'] }], googleTypes: ['sports_complex'], foursquareLabels: ['sports club'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['foil', 'epee'], specificMinScore: 0.88, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'tennis', displayLabel: 'Tennis', aliases: ['tennis', 'tennis court'], family: 'racket-sports', allowedVenueTypes: ['racket-club', 'court', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['tennis'] }, { key: 'leisure', values: ['pitch', 'sports_centre'] }], googleTypes: ['sports_complex', 'stadium'], foursquareLabels: ['tennis court', 'tennis stadium'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['tennis club'], specificMinScore: 0.82, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'badminton', displayLabel: 'Badminton', aliases: ['badminton', 'badminton court'], family: 'racket-sports', allowedVenueTypes: ['racket-club', 'court', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['badminton'] }], googleTypes: ['sports_complex'], foursquareLabels: ['badminton court'], internalTaxonomy: [] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['badminton club'], specificMinScore: 0.82, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), legacyCatalogId: 12 },
  { id: 'squash', displayLabel: 'Squash', aliases: ['squash', 'squash court'], family: 'racket-sports', allowedVenueTypes: ['racket-club', 'court'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['squash'] }], googleTypes: ['sports_complex'], foursquareLabels: ['squash court'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['squash club'], specificMinScore: 0.84, browseMinScore: 0.36, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'ping pong', displayLabel: 'Table Tennis', aliases: ['table tennis', 'ping pong', 'pingpong'], family: 'racket-sports', allowedVenueTypes: ['table-tennis-hall', 'sports-centre', 'community-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['table_tennis'] }], googleTypes: ['sports_complex'], foursquareLabels: ['table tennis room'], internalTaxonomy: [] }, hardNegatives: ['restaurant', 'bar', 'cafe', 'generic park'], confidenceWeights: weights, queryIntent: { aliases: ['table tennis hall'], specificMinScore: 0.82, browseMinScore: 0.36, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'padel', displayLabel: 'Padel', aliases: ['padel', 'pádel', 'sân padel', 'สนามพาเดล'], family: 'racket-sports', allowedVenueTypes: ['racket-club', 'court', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['padel'] }], googleTypes: ['sports_complex'], foursquareLabels: ['padel court'], internalTaxonomy: [] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['padel court', 'padel club'], specificMinScore: 0.84, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), legacyCatalogId: 16 },
  { id: 'pickleball', displayLabel: 'Pickleball', aliases: ['pickleball', 'pickle ball'], family: 'racket-sports', allowedVenueTypes: ['racket-club', 'court'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['pickleball'] }], googleTypes: ['sports_complex'], foursquareLabels: ['pickleball court'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['pickleball court'], specificMinScore: 0.86, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'football', displayLabel: 'Football', aliases: ['football', 'soccer'], family: 'team-sports', allowedVenueTypes: ['pitch', 'stadium', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['soccer'] }, { key: 'leisure', values: ['pitch', 'stadium'] }], googleTypes: ['stadium', 'sports_complex'], foursquareLabels: ['soccer field', 'stadium'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['soccer field'], specificMinScore: 0.8, browseMinScore: 0.38, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'futsal', displayLabel: 'Futsal', aliases: ['futsal', 'five a side'], family: 'team-sports', allowedVenueTypes: ['pitch', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['futsal'] }], googleTypes: ['sports_complex'], foursquareLabels: ['soccer field'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['indoor soccer'], specificMinScore: 0.84, browseMinScore: 0.36, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'basketball', displayLabel: 'Basketball', aliases: ['basketball', 'basketball court'], family: 'team-sports', allowedVenueTypes: ['court', 'sports-centre', 'stadium'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['basketball'] }], googleTypes: ['sports_complex', 'stadium'], foursquareLabels: ['basketball court'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['basketball club'], specificMinScore: 0.82, browseMinScore: 0.38, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'volleyball', displayLabel: 'Volleyball', aliases: ['volleyball', 'beach volleyball'], family: 'team-sports', allowedVenueTypes: ['court', 'pitch', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['volleyball', 'beachvolleyball'] }], googleTypes: ['sports_complex'], foursquareLabels: ['volleyball court'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['volleyball court'], specificMinScore: 0.84, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'baseball', displayLabel: 'Baseball', aliases: ['baseball'], family: 'team-sports', allowedVenueTypes: ['pitch', 'stadium'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['baseball'] }], googleTypes: ['stadium'], foursquareLabels: ['baseball field'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['baseball field'], specificMinScore: 0.88, browseMinScore: 0.28, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'softball', displayLabel: 'Softball', aliases: ['softball'], family: 'team-sports', allowedVenueTypes: ['pitch', 'stadium'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['softball'] }], googleTypes: ['stadium'], foursquareLabels: ['baseball field'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['softball field'], specificMinScore: 0.88, browseMinScore: 0.28, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'rugby', displayLabel: 'Rugby', aliases: ['rugby'], family: 'team-sports', allowedVenueTypes: ['pitch', 'stadium'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['rugby_union', 'rugby_league'] }], googleTypes: ['stadium'], foursquareLabels: ['rugby pitch'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['rugby field'], specificMinScore: 0.88, browseMinScore: 0.28, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'cricket', displayLabel: 'Cricket', aliases: ['cricket'], family: 'team-sports', allowedVenueTypes: ['pitch', 'stadium'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['cricket'] }], googleTypes: ['stadium'], foursquareLabels: ['cricket ground'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['cricket ground'], specificMinScore: 0.88, browseMinScore: 0.28, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'hockey', displayLabel: 'Hockey', aliases: ['hockey', 'field hockey', 'ice hockey'], family: 'team-sports', allowedVenueTypes: ['pitch', 'stadium'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['field_hockey', 'ice_hockey'] }], googleTypes: ['stadium'], foursquareLabels: ['hockey rink'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['hockey rink'], specificMinScore: 0.88, browseMinScore: 0.28, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'optional' }, searchable: true },
  { id: 'swimming', displayLabel: 'Swimming', aliases: ['swimming', 'swim', 'pool'], family: 'water-sports', allowedVenueTypes: ['pool', 'sports-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['swimming'] }, { key: 'leisure', values: ['swimming_pool'] }], googleTypes: ['swimming_pool', 'sports_complex'], foursquareLabels: ['pool', 'swimming pool'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['swim pool'], specificMinScore: 0.8, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'rowing', displayLabel: 'Rowing', aliases: ['rowing', 'rowing club'], family: 'water-sports', allowedVenueTypes: ['rowing-club'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['rowing'] }], googleTypes: ['sports_complex'], foursquareLabels: ['rowing club'] }, hardNegatives: ['boat tour', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['rowing club'], specificMinScore: 0.86, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'supported', bangkok: 'supported' }, searchable: true },
  { id: 'kayaking', displayLabel: 'Kayaking', aliases: ['kayaking', 'kayak'], family: 'water-sports', allowedVenueTypes: ['kayak-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['canoe', 'kayak'] }], googleTypes: ['sports_complex'], foursquareLabels: ['kayak spot', 'canoe club'] }, hardNegatives: ['boat tour', 'ferry', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['kayak club'], specificMinScore: 0.86, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'priority', bangkok: 'supported' }, searchable: true },
  { id: 'canoeing', displayLabel: 'Canoeing', aliases: ['canoeing', 'canoe'], family: 'water-sports', allowedVenueTypes: ['kayak-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['canoe'] }], googleTypes: ['sports_complex'], foursquareLabels: ['canoe club'] }, hardNegatives: ['boat tour', 'ferry', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['canoe club'], specificMinScore: 0.86, browseMinScore: 0.3, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'priority', bangkok: 'supported' }, searchable: true },
  { id: 'surf', displayLabel: 'Surfing', aliases: ['surf', 'surfing', 'surf school'], family: 'water-sports', allowedVenueTypes: ['surf-school'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['surfing'] }], googleTypes: ['school'], foursquareLabels: ['surf spot', 'surf school'] }, hardNegatives: ['beach bar', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['surf school'], specificMinScore: 0.86, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'priority', bangkok: 'optional' }, legacyCatalogId: 7 },
  { id: 'diving', displayLabel: 'Diving', aliases: ['diving', 'scuba', 'scuba diving'], family: 'water-sports', allowedVenueTypes: ['dive-centre'], preferredProviderCategories: { osmTags: [{ key: 'sport', values: ['scuba_diving'] }], googleTypes: ['school'], foursquareLabels: ['dive shop', 'dive center'] }, hardNegatives: ['boat tour', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['scuba'], specificMinScore: 0.88, browseMinScore: 0.3, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'supported', bangkok: 'optional' }, searchable: true },
  { id: 'dancing', displayLabel: 'Dance', aliases: ['dance', 'dancing', 'dance class'], family: 'dance', allowedVenueTypes: ['dance-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['dance_school', 'school'], foursquareLabels: ['dance studio'], internalTaxonomy: ['dance-choreo-workshops'] }, hardNegatives: [...consumeristHardNegatives, 'karaoke bar'], confidenceWeights: weights, queryIntent: { aliases: ['dance studio'], specificMinScore: 0.76, browseMinScore: 0.4, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'salsa', displayLabel: 'Salsa', aliases: ['salsa', 'salsa class'], family: 'dance', allowedVenueTypes: ['dance-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['dance_school'], foursquareLabels: ['dance studio'] }, hardNegatives: [...consumeristHardNegatives, 'nightclub'], confidenceWeights: weights, queryIntent: { aliases: ['salsa social'], specificMinScore: 0.82, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'bachata', displayLabel: 'Bachata', aliases: ['bachata', 'bachata class'], family: 'dance', allowedVenueTypes: ['dance-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['dance_school'], foursquareLabels: ['dance studio'] }, hardNegatives: [...consumeristHardNegatives, 'nightclub'], confidenceWeights: weights, queryIntent: { aliases: ['bachata social'], specificMinScore: 0.82, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'tango', displayLabel: 'Tango', aliases: ['tango', 'argentine tango'], family: 'dance', allowedVenueTypes: ['dance-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['dance_school'], foursquareLabels: ['dance studio'] }, hardNegatives: [...consumeristHardNegatives, 'nightclub'], confidenceWeights: weights, queryIntent: { aliases: ['tango class'], specificMinScore: 0.84, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'hip-hop', displayLabel: 'Hip Hop Dance', aliases: ['hip hop', 'hip-hop dance', 'street dance'], family: 'dance', allowedVenueTypes: ['dance-studio'], preferredProviderCategories: { googleTypes: ['dance_school'], foursquareLabels: ['dance studio'] }, hardNegatives: [...consumeristHardNegatives, 'nightclub'], confidenceWeights: weights, queryIntent: { aliases: ['hip hop class'], specificMinScore: 0.84, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'contemporary-dance', displayLabel: 'Contemporary Dance', aliases: ['contemporary dance', 'contemporary'], family: 'dance', allowedVenueTypes: ['dance-studio'], preferredProviderCategories: { googleTypes: ['dance_school'], foursquareLabels: ['dance studio'] }, hardNegatives: [...consumeristHardNegatives, 'nightclub'], confidenceWeights: weights, queryIntent: { aliases: ['contemporary class'], specificMinScore: 0.84, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'ballet', displayLabel: 'Ballet', aliases: ['ballet', 'ballet class'], family: 'dance', allowedVenueTypes: ['dance-studio'], preferredProviderCategories: { googleTypes: ['dance_school'], foursquareLabels: ['dance studio'] }, hardNegatives: [...consumeristHardNegatives, 'nightclub'], confidenceWeights: weights, queryIntent: { aliases: ['ballet studio'], specificMinScore: 0.84, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'pole-dance', displayLabel: 'Pole Dance', aliases: ['pole dance', 'pole fitness'], family: 'dance', allowedVenueTypes: ['dance-studio', 'gym'], preferredProviderCategories: { googleTypes: ['dance_school', 'gym'], foursquareLabels: ['dance studio'] }, hardNegatives: ['nightclub', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['pole studio'], specificMinScore: 0.84, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'aerial', displayLabel: 'Aerial Arts', aliases: ['aerial', 'aerial silk', 'aerial hoop'], family: 'dance', allowedVenueTypes: ['dance-studio', 'gym'], preferredProviderCategories: { googleTypes: ['dance_school', 'gym'], foursquareLabels: ['circus school'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['aerial studio'], specificMinScore: 0.86, browseMinScore: 0.3, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'chess', displayLabel: 'Chess', aliases: ['chess', 'cờ vua', 'หมากรุก', 'chess club'], family: 'social-games', allowedVenueTypes: ['chess-club', 'community-centre', 'board-game-club'], preferredProviderCategories: { googleTypes: ['community_center'], foursquareCategoryIds: ['4bf58dd8d48988d18d941735'], foursquareLabels: ['gaming cafe', 'chess club'], internalTaxonomy: [] }, hardNegatives: ['restaurant', 'bar', 'cafe', 'coffee', 'generic park'], confidenceWeights: weights, queryIntent: { aliases: ['chess club'], specificMinScore: 0.84, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), legacyCatalogId: 1 },
  { id: 'board games', displayLabel: 'Board Games', aliases: ['board games', 'board game', 'tabletop'], family: 'social-games', allowedVenueTypes: ['board-game-club', 'community-centre'], preferredProviderCategories: { googleTypes: ['community_center'], foursquareLabels: ['board game cafe', 'gaming cafe'], internalTaxonomy: ['board-game-cafes'] }, hardNegatives: ['restaurant', 'bar', 'generic park'], confidenceWeights: weights, queryIntent: { aliases: ['tabletop games'], specificMinScore: 0.82, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'billiards', displayLabel: 'Billiards', aliases: ['billiards', 'snooker'], family: 'social-games', allowedVenueTypes: ['billiards-hall'], preferredProviderCategories: { googleTypes: ['sports_complex'], foursquareLabels: ['pool hall', 'snooker hall'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['snooker hall'], specificMinScore: 0.84, browseMinScore: 0.4, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), legacyCatalogId: 5 },
  { id: 'pool', displayLabel: 'Pool', aliases: ['pool', 'pool hall', 'pool table'], family: 'social-games', allowedVenueTypes: ['billiards-hall'], preferredProviderCategories: { googleTypes: ['sports_complex'], foursquareLabels: ['pool hall'] }, hardNegatives: ['swimming pool', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['pool hall'], specificMinScore: 0.84, browseMinScore: 0.38, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'bowling', displayLabel: 'Bowling', aliases: ['bowling', 'bowling alley'], family: 'social-games', allowedVenueTypes: ['bowling-alley'], preferredProviderCategories: { googleTypes: ['bowling_alley'], foursquareCategoryIds: ['4bf58dd8d48988d1e4931735'], foursquareLabels: ['bowling alley'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['bowling alley'], specificMinScore: 0.84, browseMinScore: 0.42, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), legacyCatalogId: 2 },
  { id: 'darts', displayLabel: 'Darts', aliases: ['darts', 'dart club'], family: 'social-games', allowedVenueTypes: ['darts-club', 'community-centre'], preferredProviderCategories: { googleTypes: ['community_center'], foursquareLabels: ['sports bar', 'dart bar'] }, hardNegatives: ['bar', 'pub', 'nightclub', 'restaurant'], confidenceWeights: weights, queryIntent: { aliases: ['dart league'], specificMinScore: 0.86, browseMinScore: 0.28, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'supported', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'pottery', displayLabel: 'Pottery', aliases: ['pottery', 'pottery class'], family: 'creative-maker', allowedVenueTypes: ['maker-studio', 'art-studio'], preferredProviderCategories: { googleTypes: ['art_gallery', 'school'], foursquareLabels: ['art studio', 'ceramics studio'], internalTaxonomy: ['ceramics-and-clay-labs'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['pottery studio'], specificMinScore: 0.84, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'ceramics', displayLabel: 'Ceramics', aliases: ['ceramics', 'ceramic studio', 'clay studio'], family: 'creative-maker', allowedVenueTypes: ['maker-studio', 'art-studio'], preferredProviderCategories: { googleTypes: ['art_gallery', 'school'], foursquareLabels: ['art studio', 'ceramics studio'], internalTaxonomy: ['ceramics-and-clay-labs'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['ceramics class'], specificMinScore: 0.84, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'painting', displayLabel: 'Painting', aliases: ['painting', 'paint class'], family: 'creative-maker', allowedVenueTypes: ['art-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['art_gallery', 'school'], foursquareLabels: ['art studio'], internalTaxonomy: ['open-studio-painting'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['paint studio'], specificMinScore: 0.82, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'drawing', displayLabel: 'Drawing', aliases: ['drawing', 'sketching', 'urban sketch'], family: 'creative-maker', allowedVenueTypes: ['art-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['art_gallery', 'school'], foursquareLabels: ['art studio'], internalTaxonomy: ['urban-sketch-walks'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['drawing class'], specificMinScore: 0.82, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'crafts', displayLabel: 'Crafts', aliases: ['crafts', 'craft workshop', 'diy craft'], family: 'creative-maker', allowedVenueTypes: ['maker-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['school'], foursquareLabels: ['art studio'], internalTaxonomy: ['makerspace-build-nights', 'textile-upcycle-labs'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['craft workshop'], specificMinScore: 0.82, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'sewing', displayLabel: 'Sewing', aliases: ['sewing', 'embroidery', 'mending'], family: 'creative-maker', allowedVenueTypes: ['maker-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['school'], foursquareLabels: ['art studio'], internalTaxonomy: ['textile-upcycle-labs'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['sewing class'], specificMinScore: 0.84, browseMinScore: 0.3, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'woodworking', displayLabel: 'Woodworking', aliases: ['woodworking', 'wood shop'], family: 'creative-maker', allowedVenueTypes: ['maker-studio'], preferredProviderCategories: { googleTypes: ['school'], foursquareLabels: ['makerspace'], internalTaxonomy: ['makerspace-build-nights'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['wood shop class'], specificMinScore: 0.86, browseMinScore: 0.28, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'music-rehearsal', displayLabel: 'Music Rehearsal', aliases: ['music rehearsal', 'band practice', 'jam session'], family: 'creative-maker', allowedVenueTypes: ['music-rehearsal-space', 'community-centre'], preferredProviderCategories: { googleTypes: ['school'], foursquareLabels: ['music venue', 'rehearsal studio'], internalTaxonomy: ['jam-session-lounges'] }, hardNegatives: ['bar', 'nightclub', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['rehearsal studio'], specificMinScore: 0.84, browseMinScore: 0.3, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'photography', displayLabel: 'Photography', aliases: ['photography', 'photo walk', 'photo class'], family: 'creative-maker', allowedVenueTypes: ['photo-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['art_gallery', 'school'], foursquareLabels: ['photo studio'], internalTaxonomy: ['street-photography-missions'] }, hardNegatives: [...creativeNegatives, ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['photography class'], specificMinScore: 0.82, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'meditation', displayLabel: 'Meditation', aliases: ['meditation', 'meditation class'], family: 'wellness', allowedVenueTypes: ['wellness-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['meditation_center', 'yoga_studio'], foursquareLabels: ['meditation center'], internalTaxonomy: [] }, hardNegatives: [...consumeristHardNegatives, 'generic park'], confidenceWeights: weights, queryIntent: { aliases: ['meditation centre'], specificMinScore: 0.82, browseMinScore: 0.34, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'breathwork', displayLabel: 'Breathwork', aliases: ['breathwork', 'breath work'], family: 'wellness', allowedVenueTypes: ['wellness-studio', 'community-centre'], preferredProviderCategories: { googleTypes: ['meditation_center', 'yoga_studio'], foursquareLabels: ['meditation center'], internalTaxonomy: [] }, hardNegatives: [...consumeristHardNegatives, 'generic park'], confidenceWeights: weights, queryIntent: { aliases: ['breathwork class'], specificMinScore: 0.84, browseMinScore: 0.3, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('supported'), searchable: true },
  { id: 'sauna', displayLabel: 'Sauna', aliases: ['sauna', 'sauna session'], family: 'wellness', allowedVenueTypes: ['sauna-studio', 'wellness-studio'], preferredProviderCategories: { googleTypes: ['spa'], foursquareLabels: ['sauna / steam room'] }, hardNegatives: ['massage', 'salon', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['sauna studio'], specificMinScore: 0.86, browseMinScore: 0.26, requireStrongEvidenceForSpecific: true }, launchCityRelevance: { hanoi: 'optional', 'da-nang': 'optional', bangkok: 'supported' }, searchable: true },
  { id: 'language-exchange', displayLabel: 'Language Exchange', aliases: ['language exchange', 'language meetup'], family: 'community', allowedVenueTypes: [...communityIndoor], preferredProviderCategories: { googleTypes: ['community_center'], foursquareLabels: ['community center'], internalTaxonomy: ['language-exchange-lounges'] }, hardNegatives: ['bar', 'nightclub', ...consumeristHardNegatives], confidenceWeights: weights, queryIntent: { aliases: ['language meetup'], specificMinScore: 0.8, browseMinScore: 0.32, requireStrongEvidenceForSpecific: true }, launchCityRelevance: launchAll('priority'), searchable: true },
  { id: 'volunteering', displayLabel: 'Volunteering', aliases: ['volunteering', 'volunteer'], family: 'community', allowedVenueTypes: [...communityIndoor, 'park'], preferredProviderCategories: { googleTypes: ['community_center'], foursquareLabels: ['community center'], internalTaxonomy: ['volunteer-blitz-days', 'neighborhood-clean-walks'] }, hardNegatives: consumeristHardNegatives, confidenceWeights: weights, queryIntent: { aliases: ['volunteer group'], specificMinScore: 0.74, browseMinScore: 0.3, requireStrongEvidenceForSpecific: false }, launchCityRelevance: launchAll('supported'), searchable: true },
] as const satisfies readonly BaseCanonicalActivityDefinition[];

export const canonicalActivityDefinitions: readonly CanonicalActivityDefinition[] = CANONICAL_ACTIVITY_DEFINITIONS.map((definition) => ({
  ...definition,
  launchVisibility: resolveLaunchVisibilityPolicy(definition),
}));

export type CanonicalActivityId = (typeof CANONICAL_ACTIVITY_DEFINITIONS)[number]['id'];

export const searchableCanonicalActivityIds = canonicalActivityDefinitions
  .filter((entry) => entry.searchable !== false)
  .map((entry) => entry.id) as readonly CanonicalActivityId[];
