-- Database update entrypoint (Step 5 · December 2025)
--
-- This script now documents how to run the canonical Supabase migrations stored under
-- apps/doWhat-web/supabase/migrations. Instead of pasting ad-hoc SQL here, rely on
-- the migration runner so every environment (dev, staging, prod) remains in sync.
--
-- Quick start
-- ==========
-- 1. Export a Supabase/Postgres connection string with DDL privileges:
--      export SUPABASE_DB_URL="postgres://postgres:password@host:6543/postgres"
--      # DATABASE_URL works too – run_migrations.js checks both env vars.
-- 2. Apply every pending migration (including 025–031) via the Node runner:
--      pnpm run db:migrate
--      # alias for: node run_migrations.js
-- 3. (Optional) Reseed helper data once migrations complete:
--      pnpm seed:taxonomy
--      pnpm seed:places:bangkok
--      pnpm seed:events:bangkok
--      # scripts live under /scripts and rely on SUPABASE service keys.
--
-- Migration roster (025–034)
-- ==========================
-- 025_places_foursquare_metadata.sql      → Adds city + foursquare_id columns + indexes on places.
-- 026_activity_catalog.sql                → Introduces the catalog tables, triggers, and baseline seeds.
-- 027_sessions_attendance.sql             → Refreshes sessions + attendance schema (host ids, policies, indexes).
-- 028_sessions_schema_spec.sql            → Aligns sessions/session_attendees with the published spec.
-- 028_sessions_schema_spec_rollback.sql   → Restores the pre-spec constraints (set-null/cascade) if needed.
-- 029_remove_rsvps_table.sql              → Drops the final legacy rsvps table.
-- 029_remove_rsvps_table_rollback.sql     → Recreates a minimal rsvps table for emergency rollbacks.
-- 030_attendance_views.sql                → Adds the session/activity/venue attendance rollup views.
-- 031_user_saved_activities.sql           → Creates the saved activities table, views, and RLS policies.
-- 032_trait_policy_guard_fix.sql          → Hardens trait policy guardrails (see docs/trait_policies_test_plan.md).
-- 033_remove_event_participants.sql       → Cleans up the deprecated event_participants table + triggers.
-- 034_admin_audit_logs.sql                → Adds admin_allowlist + admin_audit_logs with RLS-backed inserts/selects.
-- 034a_extend_attendance_status.sql       → Adds the 'registered' and 'late_cancel' enum values ahead of Social Sweat.
-- 035_social_sweat_core.sql               → Adds reliability columns, sport metadata, `user_sport_profiles`,
--                                            `session_open_slots`, and related enums/triggers for the Social Sweat workstream.
-- 036_attendance_reliability_trigger.sql  → Moves reliability scoring into Postgres triggers tied to session_attendees.
-- 037_reliability_pledge_ack.sql          → Adds columns so profiles can track reliability pledge acknowledgements + versions.
--
-- Validation + rollback guidance now lives in docs/migrations_025-031_validation.md.
-- Run `git diff -- apps/doWhat-web/supabase/migrations` before/after releases to confirm
-- no unexpected edits landed outside the numbered files.
--
-- NOTE: This file intentionally contains no executable SQL anymore. All schema changes must
-- flow through the numbered migrations to keep Supabase environments reproducible.
