import type { ActivityCatalogEntry } from './types';

export const ACTIVITY_CATALOG_PRESETS: ActivityCatalogEntry[] = [
  {
    id: 1,
    slug: 'chess',
    name: 'Chess',
    description: 'Quiet venues that host chess meetups, clubs, or lessons.',
    keywords: ['chess', 'chess club', 'chess cafe', 'board game', 'board games', 'cờ vua', 'หมากรุก'],
    fsq_categories: ['4bf58dd8d48988d18d941735'],
  },
  {
    id: 2,
    slug: 'bowling',
    name: 'Bowling',
    description: 'Alleys and entertainment spaces with bowling lanes.',
    keywords: ['bowling', 'bowling alley', 'bowling lanes'],
    fsq_categories: ['4bf58dd8d48988d1e4931735'],
  },
  {
    id: 3,
    slug: 'climbing',
    name: 'Climbing & Bouldering',
    description: 'Indoor climbing gyms and bouldering studios.',
    keywords: [
      'climbing',
      'rock climbing',
      'climbing gym',
      'bouldering',
      'boulder gym',
      'sala escalada',
      'leo nui',
      'phong tap leo nui',
      'ยิมปีนผา',
      'โบลเดอร์',
    ],
    fsq_categories: ['4bf58dd8d48988d1e1931735'],
  },
  {
    id: 4,
    slug: 'yoga',
    name: 'Yoga',
    description: 'Studios focused on yoga, stretching, or meditation.',
    keywords: ['yoga', 'yoga studio', 'meditation', 'stretching', 'thiền', 'โยคะ'],
    fsq_categories: ['4bf58dd8d48988d102941735'],
  },
  {
    id: 5,
    slug: 'billiards',
    name: 'Billiards & Pool',
    description: 'Pool halls, billiards clubs, and snooker venues.',
    keywords: ['billiards', 'pool hall', 'pool club', 'snooker', 'pool table'],
    fsq_categories: [],
  },
  {
    id: 6,
    slug: 'massage',
    name: 'Massage & Spa',
    description: 'Massage shops, wellness spas, and recovery centers.',
    keywords: ['massage', 'thai massage', 'spa', 'wellness', 'onsen'],
    fsq_categories: [],
  },
  {
    id: 7,
    slug: 'surf',
    name: 'Surf',
    description: 'Surf schools, surf camps, and wave sports operators.',
    keywords: ['surf', 'surfing', 'surf school', 'wave', 'kitesurf'],
    fsq_categories: [],
  },
  {
    id: 8,
    slug: 'boating',
    name: 'Boating & Water Tours',
    description: 'Boat tours, ferry piers, kayaking, and paddle activities.',
    keywords: ['boat', 'boating', 'ferry', 'pier', 'cruise', 'kayak', 'paddle'],
    fsq_categories: [],
  },
  {
    id: 9,
    slug: 'martial-arts',
    name: 'Martial Arts',
    description: 'Muay Thai, boxing gyms, and combat sport schools.',
    keywords: ['muay thai', 'boxing', 'kickboxing', 'martial arts', 'dojo'],
    fsq_categories: [],
  },
  {
    id: 10,
    slug: 'running',
    name: 'Running',
    description: 'Running clubs, tracks, and park routes.',
    keywords: [
      'running',
      'run club',
      'jogging',
      'track',
      'stadium',
      'park run',
      'chạy bộ',
      'đường chạy',
      'วิ่ง',
      'ลู่วิ่ง',
    ],
    fsq_categories: [],
  },
  {
    id: 11,
    slug: 'cycling',
    name: 'Cycling',
    description: 'Cycling hubs, bike tracks, and spin studios.',
    keywords: ['cycling', 'bike', 'bicycle', 'velodrome', 'spin class'],
    fsq_categories: [],
  },
  {
    id: 12,
    slug: 'badminton',
    name: 'Badminton',
    description: 'Badminton courts and clubs.',
    keywords: ['badminton', 'badminton court'],
    fsq_categories: [],
  },
  {
    id: 13,
    slug: 'roller-skating',
    name: 'Roller Skating',
    description: 'Roller rinks, inline skating spaces, and skate facilities.',
    keywords: ['roller skating', 'rollerskating', 'roller rink', 'inline skating', 'skating', 'skate park'],
    fsq_categories: [],
  },
  {
    id: 14,
    slug: 'horse-riding',
    name: 'Horse Riding',
    description: 'Equestrian clubs, horse riding schools, and stables.',
    keywords: ['horse riding', 'horseback riding', 'equestrian', 'stable', 'riding school'],
    fsq_categories: [],
  },
  {
    id: 15,
    slug: 'poker',
    name: 'Poker',
    description: 'Poker rooms, card clubs, and venues that host poker games.',
    keywords: ['poker', 'poker room', 'poker club', 'card room', 'texas hold em', 'holdem', 'casino poker', 'casino'],
    fsq_categories: [],
  },
  {
    id: 16,
    slug: 'padel',
    name: 'Padel',
    description: 'Padel courts and clubs for singles or doubles sessions.',
    keywords: ['padel', 'pádel', 'padel court', 'padel club', 'sân padel', 'สนามพาเดล'],
    fsq_categories: [],
  },
  {
    id: 17,
    slug: 'bouldering',
    name: 'Bouldering',
    description: 'Indoor bouldering gyms and climbing walls.',
    keywords: ['bouldering', 'boulder gym', 'climbing gym', 'sala escalada', 'โบลเดอร์'],
    fsq_categories: [],
  },
];

export const getActivityPresetById = (id: number): ActivityCatalogEntry | undefined =>
  ACTIVITY_CATALOG_PRESETS.find((entry) => entry.id === id);

export const getActivityPresetBySlug = (slug: string): ActivityCatalogEntry | undefined =>
  ACTIVITY_CATALOG_PRESETS.find((entry) => entry.slug === slug);
